<?php

return [
    'admin.index' => 'Trang chủ admin',
    'admin.thong-tin-ca-nhan' => 'Thông tin cá nhân',
    'admin.nhan-su.danh-sach' => 'Danh sách nhân sự',
    'admin.lich-chup' => 'Lịch chụp',
    'admin.lich-shop' => 'Lịch shop',
    'admin.note-khach-moi' => 'Note khách mới',
    'admin.bao-cao.ads' => 'Báo cáo Ads',
    'admin.khach-hang.tao-hop-dong' => 'Tạo hợp đồng cưới',
    'admin.khach-hang.tao-hop-dong-canh-bao' => 'Cảnh báo mã hợp đồng tạo hợp đồng',
    'admin.tu-van.danh-sach' => 'Danh sách đăng ký tư vấn',
    'admin.trang-phuc.san-pham' => 'Sản phẩm trang phục',
    'admin.trang-phuc.hop-dong' => 'Hợp đồng trang phục',
    'admin.dich-vu.dich-vu-le' => 'Dịch vụ lễ',
    'admin.dich-vu.nhom-dich-vu' => 'Nhóm dịch vụ',
    'admin.tai-chinh.cong-no' => 'Công nợ',
    'admin.tai-chinh.phieu-thu-chi' => 'Phiếu thu chi',
    'admin.tai-chinh.tinh-luong' => 'Tính lương',
    'admin.diem-danh.diem-danh' => 'Điểm danh',
    'admin.concept.concept' => 'Concept',
    'admin.diem-danh.cham-cong' => 'Chấm công',
    'admin.diem-danh.check-in' => 'Check-in',
    'admin.diem-danh.check-out' => 'Check-out',
    'admin.diem-danh.nghi-phep' => 'Nghỉ phép',
    'admin.nhan-su.cong-viec-cua-toi' => 'Công việc của tôi',
    'admin.khach-hang.danh-sach-hop-dong-cuoi' => 'Danh sách hợp đồng cưới',
    'admin.khach-hang.hop-dong-cuoi.dieu-phoi' => 'Điều phối hợp đồng cưới (modal)',
    'admin.khach-hang.hop-dong-cuoi.dieu-phoi.nhan-vien-theo-ngay' => 'Danh sách nhân viên theo ngày chụp (modal điều phối)',
    'admin.khach-hang.chinh-sua-hop-dong-cuoi' => 'Chỉnh sửa hợp đồng cưới',
    'admin.he-thong.ip-diem-danh' => 'IP điểm danh',
    'admin.he-thong.ca-lam-viec' => 'Ca làm việc',
    'admin.he-thong.tai-lieu' => 'Tài liệu hệ thống',
];
